In [12]:
import numpy as np
import random
import igl
import trimesh as tri
from IPython.core.display import display, HTML

random.seed(42)

data_dir = "data/"
#files = ["ChineseLion.obj",
#         "Femur.obj",
#         "Foot.obj",
#         "Hat.obj",
#         "HumanBrain.obj",
#         "HumanFace.obj",
#         "Nefertiti.obj",
#         "OldMan.obj",
#         "StanfordBunny.obj",
#         "spot_triangulated.obj"]
#files = ["StanfordBunny.obj"]
files = ["spot_triangulated.obj"]

C:\Users\Student\AppData\Local\Temp\ipykernel_19952\123263175.py:5: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


In [13]:
def display_cut(vertex_positions, indicies, full_cut):
    trimesh = tri.Trimesh(vertices=vertex_positions, faces=indicies) 
    scene = tri.Scene(trimesh)
    for cut in full_cut:
        if len(cut) == 4:
            continue
        cut_verticies = vertex_positions[cut]
        range = np.arange(2, len(cut))
        line_range= tri.path.entities.Line(points=range,color=np.array([[255,0,0,255]]))
        path1 = tri.path.path.Path3D(entities=[line_range], vertices=cut_verticies)
        scene.add_geometry(path1)
    scene.show(viewer='gl')

def cut_and_parameterize(M, p, n):
    values =  np.zeros((n , n, 3))
    normals = np.zeros((n, n, 3))

    #pcd = M.sample_points_uniformly(number_of_points=n*n)

In [14]:
#n = int(input("What size geometry image would you like? "))

for file in files:
    # Read in the vertex positions of the geometry
    # Read in the indicies of the triangle mesh 
    vertex_positions, indicies = igl.read_triangle_mesh("%s%s"%(data_dir, file))

    print("vertex_pos shape: ", vertex_positions.shape) 
    print("vertex_pos head: \n", vertex_positions[:10])
    print("indicies shape: ", indicies.shape)
    print("indicies head: \n", indicies[:10])

    boundary = igl.boundary_loop(indicies)
    print("boundary length: ", len(boundary))

    seed_removed_indicies = np.delete(indicies, random.randint(0, len(indicies)), axis=0)
    if len(boundary) == 0:
        seed_removed_indicies = np.delete(seed_removed_indicies, random.randint(0, len(seed_removed_indicies)), axis=0)

    initial_cut = igl.cut_to_disk(seed_removed_indicies)

    for cut in initial_cut:
        cut_verticies = vertex_positions[cut]
        print("cut head: \n", cut[2:12])
        print("cut points: \n", cut_verticies[2:12] )
        print("cut lines head: \n", np.array(tuple(zip(cut_verticies[:-1][2:12], cut_verticies[1:][2:12]))))

    display_cut(vertex_positions=vertex_positions, indicies=indicies, full_cut=initial_cut)


vertex_pos shape:  (2930, 3)
vertex_pos head: 
 [[ 0.348799   -0.334989   -0.0832331 ]
 [ 0.313132   -0.399051    0.881192  ]
 [ 0.266758    0.181628    0.122726  ]
 [ 0.229555    0.0663178   0.828702  ]
 [ 0.353623   -0.0486456   0.443969  ]
 [ 0.335878   -0.384495    0.425693  ]
 [ 0.305362    0.0307983  -0.00655663]
 [ 0.279611   -0.0552387   0.858547  ]
 [ 0.266719    0.10578     0.46681   ]
 [ 0.149341   -0.451522    0.166423  ]]
indicies shape:  (5856, 3)
indicies head: 
 [[738 734 735]
 [188 735 734]
 [191 737 736]
 [738 736 737]
 [189 740 739]
 [742 739 740]
 [735 188 742]
 [741 742 188]
 [744 746 190]
 [743 190 746]]
boundary length:  0
cut head: 
 [2510, 2507]
cut points: 
 [[-0.0713902  -0.00682142 -0.215572  ]
 [-0.101087   -0.0620719  -0.200364  ]]
cut lines head: 
 [[[-0.0713902  -0.00682142 -0.215572  ]
  [-0.101087   -0.0620719  -0.200364  ]]]
cut head: 
 [1445, 1457]
cut points: 
 [[ 0.219301  0.191387 -0.600189]
 [ 0.21995   0.228648 -0.628685]]
cut lines head: 
 [[[ 