In [6]:
! pip install -r requirements.txt

  Cloning https://github.com/skoch9/meshplot.git to c:\users\student\appdata\local\temp\pip-req-build-52aq2atz
  Resolved https://github.com/skoch9/meshplot.git to commit 725e4a7926a5f10888f0edd1762fecf9db751c56


  Running command git clone -q https://github.com/skoch9/meshplot.git 'C:\Users\Student\AppData\Local\Temp\pip-req-build-52aq2atz'
You should consider upgrading via the 'C:\Users\Student\Documents\College\Sem7\CS_6501-Geometry_of_Data\project\env\Scripts\python.exe -m pip install --upgrade pip' command.


In [14]:
import numpy as np
#import open3d as o3d
import random
import igl
import scipy
import meshplot as mp
from IPython.core.display import display, HTML

# Comment out these functions when running offline, as they are not needed
def plot_mesh(v, f, colors=None) :
   data = mp.plot(v,f,c=colors,s=[2,2,0])
   display(HTML(data.to_html()))
   return data

def subplot_mesh(v, f, d, colors=None) :
   display(HTML(mp.subplot(v,f,c=colors,s=[2,2,0],data=d).to_html()))

random.seed(42)

data_dir = "data/"
#files = ["ChineseLion.obj",
#         "Femur.obj",
#         "Foot.obj",
#         "Hat.obj",:w

#         "HumanBrain.obj",
#         "HumanFace.obj",
#         "Nefertiti.obj",
#         "OldMan.obj",
#         "StanfordBunny.obj"]
files = ["StanfordBunny.obj"]


C:\Users\Student\AppData\Local\Temp\ipykernel_15276\3769076147.py:7: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


In [15]:
# n = int(input("What size geometry image would you like? "))
n = 100

meshes = []
for file in files:
    # Read in the vertex positions of the geometry
    # Read in the indicies of the triangle mesh 
    vertex_positions, indicies = igl.read_triangle_mesh("%s%s"%(data_dir, file))
    data = plot_mesh(vertex_positions, indicies)

    # Find the open boundary to map to the square
    # 
    # igl.boundary_loop will calculate an ordered list of boundary vertices of the 
    # longest boundary loop
    boundary = igl.boundary_loop(indicies)
    boundary_verticies = vertex_positions[boundary]
    print("vertex_pos shape: ", vertex_positions.shape) 
    print("vertex_pos head: \n", vertex_positions[:10])
    print("indicies shape: ", indicies.shape)
    print("indicies head: \n", indicies[:10])
    print("boundary head: \n", boundary[:10])
    print("boundary verticies: \n", boundary_verticies[:10])
    data.add_lines(boundary_verticies[1:], boundary_verticies[:-1])


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.336809…

vertex_pos shape:  (32717, 3)
vertex_pos head: 
 [[ 0.110202  0.74011   1.1324  ]
 [-1.57671   1.97364  -0.037372]
 [-1.27692  -0.26665   0.84513 ]
 [ 0.16809  -0.278324 -0.459728]
 [ 1.11901   0.016062  0.104106]
 [ 0.210986  1.44328  -0.23301 ]
 [-1.51855   1.16822   0.752842]
 [ 0.34706  -0.251982  0.860968]
 [-0.415494  0.456972 -0.775864]
 [ 0.257834  1.55146   0.545838]]
indicies shape:  (65221, 3)
indicies head: 
 [[    0  8127 19192]
 [ 8127     0 30683]
 [    0 19192 19191]
 [    0 19191 25992]
 [    0 25992 30403]
 [    0 30403 30683]
 [ 6625     1 21001]
 [    1  6625 24803]
 [    1  9891 15778]
 [    1 24803  9891]]
boundary head: 
 [  171 25069  4390 18073  1279 24549  6531 20119 10216 23726]
boundary verticies: 
 [[-0.362908 -0.304044  0.902012]
 [-0.343078 -0.304882  0.907044]
 [-0.32242  -0.304138  0.91073 ]
 [-0.303422 -0.306552  0.916914]
 [-0.288934 -0.303848  0.882446]
 [-0.269128 -0.304686  0.887398]
 [-0.248474 -0.303948  0.891112]
 [-0.228676 -0.304788  0.896054]

In [ ]:
def cut_and_parameterize(M, p, n):
    values =  np.zeros((n , n, 3))
    normals = np.zeros((n, n, 3))

    #pcd = M.sample_points_uniformly(number_of_points=n*n)